export enum OrderStatus {
  ORDER_CREATED = 'ORDER_CREATED',
  ITEMS_ADDED = 'ITEMS_ADDED',
  ITEMS_CANCELLED = 'ITEMS_CANCELLED',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
